// <auto-generated />
using System;
using HomeLabMonitoring.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeLabMonitoring.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeLabMonitoring.Api.Models.DiskMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiskAvailable")
                        .HasColumnType("bigint");

                    b.Property<long>("DiskTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MountPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiskMetrics");
                });

            modelBuilder.Entity("HomeLabMonitoring.Api.Models.HostMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CPU")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LoadAverage15m")
                        .HasColumnType("double precision");

                    b.Property<double>("LoadAverage1m")
                        .HasColumnType("double precision");

                    b.Property<double>("LoadAverage5m")
                        .HasColumnType("double precision");

                    b.Property<long>("MemoryTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkDownload")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkDownloadSpeed")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkUpload")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkUploadSpeed")
                        .HasColumnType("bigint");

                    b.Property<long>("Uptime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HostMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
